version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
  parse:
    image: ldelriof/parse
    restart: always
    depends_on:
      - "mongodb"
    environment:
      APPLICATION_ID: parseid
      MASTER_KEY: masterkey
      DATABASE_URI:  mongodb://root:rootpassword@mongodb/test?authSource=admin
    ports:
        - 1337:1337
  iop-node:
    image: ldelriof/iop-node
    command: iop-node
    depends_on:
      - "parse"
    restart: always
    environment: 
      IOP_NODE_ID: uniquenodeid
      IOP_HOST: http://parse:1337
    links:
      - parse:parse
volumes:
  mongodb_data_container:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data'
